### ISSUE TITLE
jpype.startJVM is crashing in Windows 7

### ISSUE THREAD

**Issue by dhgary** [jpype-project/jpype#148]
I have installed jpype 0.6.0 on two Windows 7 machines using setup.py.  The install appears to run with no problems.  I can successfully import jpype.  I can successfully check if the JVM is started.  I can successfully get the JVM path.

> > > import jpype
> > > jpype.**version**
> > > '0.6.0'
> > > jpype.isJVMStarted()
> > > 0
> > > jpype.getDefaultJVMPath()
> > > u'C:\Program Files (x86)\Java\jre1.7.0_80\bin\client\jvm.dll'

When I start the JVM in the pythonwin interactive window, pythonwin crashes.  Tried the Idle interactive window, it also crashes.  This happens on both of my Windows 7 machines.

javaPath = the path to my ‘jar’ file.  I tried a few ‘jar’ files I have used in the past.

> > > jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=%s" % javaPath)

Also tried the simplest thing I could, same results.

> > > jpype.startJVM(jpype.getDefaultJVMPath())

I previously was running jpype 0.5.4 and it works fine.  I’ve tried everything I can think of to trace the problem with no results.  Has anyone else experienced this?  Thanks for any help. -Gary

**Comment by baztian** [comment]
Do you have a stacktrace?
At what line does the crash happen?
At jpype.startJVM or later?
How did you install it? Which compiler or binary did you use?

**Comment by dhgary** [comment]
Thank you for your response.  I have tried this on three different machines with the same result.  Here are the details:
Windows 7
jpype  0.6.0
Python 2.7.10 – I read something yesterday that said jpype 0.6.0 is Python 3.X specific.  True?  If true, that would be the problem.

I installed by running setup.py build and install.

On one machine I have Visual Studio 2013 installed.

The other two machines I downloaded Microsoft visual C++ compiler package for Python 2.7

I do the following in the pythonwin or idle interactive window:
import jpype
I confirm I am running 0.6.0 by jpype.__version__
The crash occurs when startJVM is executed.
jpype.startJVM(jpype.getDefaultJVMPath())
Via pythonwin, an exception occurs in the pythonwin.exe.
Via Idle, an exception occurs in the pythonw.exe.

**Comment by baztian** [comment]
What error message / stacktrace do you get when run from the command line via python.exe (not pythonw or idle)?

**Comment by dhgary** [comment]
Java version 1.7.0_80

I created a script with this code:

import jpype
print jpype.getDefaultJVMPath()
print jpype.isJVMStarted()
jpype.startJVM(jpype.getDefaultJVMPath())
print jpype.isJVMStarted()

Run from command line:

C:\tmp>c:\python27\python script1.py

The following was recorded from Process Explorer:

Fault info:

Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x5560ad83
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00820005
Faulting process id: 0x10f0
Faulting application start time: 0x01d0df7a43d992ae
Faulting application path: c:\python27\python.exe
Faulting module path: unknown
Report Id: 81a2ae28-4b6d-11e5-bc78-0023ae9a767a
Exception msg: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

Stack:

ntoskrnl.exe!memset+0x61a
ntoskrnl.exe!KeWaitForMultipleObjects+0xd52
ntoskrnl.exe!KeWaitForSingleObject+0x19f
ntoskrnl.exe!PoStartNextPowerIrp+0xba4
ntoskrnl.exe!PoStartNextPowerIrp+0x1821
ntoskrnl.exe!KeWaitForMultipleObjects+0xf5d
ntoskrnl.exe!KeWaitForMultipleObjects+0x26a
ntoskrnl.exe!NtWaitForSingleObject+0x40f
ntoskrnl.exe!IoReportTargetDeviceChange+0xe71
ntoskrnl.exe!KeSynchronizeExecution+0x3a23
wow64cpu.dll!TurboDispatchJumpAddressEnd+0x6c0
wow64cpu.dll!TurboDispatchJumpAddressEnd+0xf5
wow64.dll!Wow64SystemServiceEx+0x1ce
wow64.dll!Wow64LdrpInitialize+0x42a
ntdll.dll!RtlUniform+0x6e6
ntdll.dll!EtwEventSetInformation+0x14e0c
ntdll.dll!LdrInitializeThunk+0xe
ntdll.dll!NtWaitForMultipleObjects+0x15
kernel32.dll!WaitForMultipleObjectsEx+0x8e
kernel32.dll!WaitForMultipleObjects+0x18
kernel32.dll!GetApplicationRecoveryCallback+0x2a7
kernel32.dll!GetApplicationRecoveryCallback+0x166
kernel32.dll!UnhandledExceptionFilter+0x161
kernel32.dll!UnhandledExceptionFilter+0xe0
ntdll.dll!RtlKnownExceptionFilter+0xb7
ntdll.dll!RtlInitializeExceptionChain+0x36

**Comment by dhgary** [comment]
Not sure if this will help, but here is some output I captured from windbg.

**Comment by OctThe16th** [comment]
I'm having the same issue with Python 2.7.10 on windows 10, python simply crashes on  jpype.startJVM on my two computers.

**Comment by marscher** [comment]
64 bit python with 32bit java or vice versa, maybe? These configurations can not work (will crash) and there is no way to catch these culprits via the program (not to my knowledge, but please tell me if I'm wrong).

**Comment by OctThe16th** [comment]
32 bit python and 32 bit java, I'm at a complete loss, getDefaultJVMPath() leads me to the 32 bit installation as well

**Comment by marscher** [comment]
Have you compiled yourself or installed with conda and conda-forge channel?

**Comment by dhgary** [comment]
I don’t have anything to add to my original question.  I do have access to an older 32 bit laptop.  When I have time I will test in that environment and update you.

gs

**Comment by dhgary** [comment]
My work computer is 64 bit.  I have only 32 bit Python 2.7.12 installed.  I have both 32 bit and 64 bit java installed.  This is the same computer I was using when I originally posted the problem.

Today I installed Python 2.7.12 and the latest pywin32 on an old 32 bit laptop.  I copied the jpype pyd and folders from my work computer to the 32 bit laptop.  In the Pythonwin interactive window I am able to successfully start the JVM using the jar file required for my project.

Even though on my work computer, testing appears to indicate I am accessing the 32 bit version of java, I have to wonder if a conflict exists.

**Comment by mansoorfayyaz** [comment]
@dhgary @OctThe16th 
Has anybody found the solution to this. Im also getting the same problem in windows 10  running python 3.6, 32 bit and jre 32 bit.
```
from jpype import *
startJVM('C:\\Program Files (x86)\\Java\\jre1.8.0_131\\bin\\client\\jvm.dll' "-ea")
java.lang.System.out.println("hello world")
shutdownJVM()
```
at startJVM(), the python crashes when running from command line.
When I run this code in pyCharm CE, at startJVM() it gives the error.

Any solutions or suggestions? 
Thanks

**Comment by dhgary** [comment]
We have not.  We tested the latest jpype release for python 2.7 with the same results.

**Comment by vidishasharma** [comment]
Same problem, I installed pip install JayDeBeApi  on 32bit  python and then ran some jdbc stuff and it simply crashes.

Any solution to this ?

**Comment by dhgary** [comment]
I haven’t found one.  It does work on an old Win 7 32 bit machine.  But that doesn’t help in real life.

**Comment by marscher** [comment]
please report this to JayDeBeAPI. I do not know how jpype is used there
exactly. We run CI tests for Windows, which does not seem to be the case
for the mentioned project.

@orginell: could you have a look please?

**Comment by ramkv** [comment]
I'm not sure if this is going to help others but what worked for me was doing a fresh install without the cache.

pip install -U Jpype1 

and java home set as   "set JAVA_HOME=C:\Progra~2\Java\jdk1.8.0_161"  ie no spaces before the install and during the execution.

**Comment by seva0stapenko** [comment]
@ramkv - that was it.
In my case the issue was solved just by using 8.3 name for JAVA_HOME.

**Comment by dhgary** [comment]
It’s still crashing PythonWin and Idle for me.  I’m curious if there are any other changes you’ve made.

>>> import jpype
>>> jpype.getDefaultJVMPath()
'C:\\PROGRA~2\\Java\\jre1.8.0_181\\bin\\client\\jvm.dll'
>>> jpype.startJVM(jpype.getDefaultJVMPath())  <-- dies on this command


Also tried
'C:\\PROGRA~2\\Java\\ JRE18~2.0_1\\bin\\client\\jvm.dll'

Thanks

Gary

**Comment by seva0stapenko** [comment]
@dhgary 
The sequence that worked for me (based on @ramkv post) was:
1. Uninstall JPype1 and remove all possible left over folders under lib/site-packages.
2. In a command window set JAVA_HOME as set JAVA_HOME=C:\Progra~2\Java\jdk1.8.0_181 (do not enclose 8.3 path into double quotes).
3. Install Jpype1 with --no-cache-dir option (pip --no-cache-dir install jpype1).

After that the test mini-program started working. Before that it was crashing python.exe with access violation at the same point as in your case.

I tend to believe that there is an issue with JPype1 setup/linking step when JAVA_HOME is not set or set to a path with spaces in it.

As soon as correctly installed/linked on my Win 7 JPype works with both JRE 7 and JRE 8 and I can use regular windows paths with spaces to jvm.dll

**Comment by dhgary** [comment]
Thanks you for the information.  I remember trying this before.  Went through the process again and it still doesn’t work for me.  Tried it on a few different machines via pip and all crash as I described previously.

I decided to do a search on ‘jpype’ binary to see if anyone has posted a compiled version at a site I could trust.  I found an educational institution that has a jpype wheel for Python 2.7 32 bit (latest jpype version) so I decided to give it a roll.  Installed and tried to import jpype and receive a can’t import numpy error???  OK, installed numpy and things appear to work fine with Python 2.7.15.  No idea why numpy is required.  Also, no need to set JAVA_HOME, works fine with ‘Program Files (x86)’.  I need to do some more testing, but this looks promising for what I need.
