### ISSUE TITLE
Memory leak when using JProxy with instance containing Java member

### ISSUE THREAD

**Issue by jaseg** [jpype-project/jpype#276]
On the java side, the following code will leak Strings and Runnables all over the place. The problem seems to be the reference of the ```Test``` instance to ```data```. If this is rewritten ```inst=Test(None)```, nothing is leaked.

```python
#!/usr/bin/env python3

from jpype import *

startJVM(getDefaultJVMPath())

class Test:
    def __init__(self, data):
        self.data = data

    def run(self):
        pass

for _ in range(1000):
    data = JString('foobar'*10000)
    proxy = JProxy('java.lang.Runnable', inst=Test(data))
    del proxy
    del data
```

**Comment by marscher** [comment]
Which version did you use? We fixed some leaks on master recently.

**Comment by jaseg** [comment]
I am using v0.6.2 from PyPI. I just retried with a fresh install from master and the problem persists.

**Comment by jaseg** [comment]
I'm not even close to properly understanding this, but it looks to me as if two references to the container jpype.JProxy python object leak in this case. The following test script prints two (three including the temporary reference passed to ```sys.getrefcount```) for the host python ```jpype.JProxy``` object after all python references to it have been deleted. This looks two too high to me.

```python
import sys
import gc
import pprint

from jpype import *

startJVM(getDefaultJVMPath(), '-Xrs', '-Djava.compiler=NONE')

class Test:
    def __init__(self, data):
        self.data = data

    def run(self):
        pass

print('CREATING DATA', file=sys.stderr)
data = JString('foobar')#*10000)
print('CREATING PROXY', file=sys.stderr)
proxy = JProxy('java.lang.Runnable', inst=Test(data))
print('PRE GC', file=sys.stderr)
print('\033[91mproxy refcount:\033[0m', sys.getrefcount(proxy)-1)
del proxy
print('\033[91mproxy refcount:\033[0m', sys.getrefcount([o for o in gc.get_objects() if 'proxy' in str(type(o)).lower()][0])-1)
print('\033[91mproxy referrers:\033[0m')
pprint.pprint(gc.get_referrers([o for o in gc.get_objects() if 'proxy' in str(type(o)).lower()][0]))
del data

gc.collect()
print('POST GC', file=sys.stderr)
```

Doing a brief review of the involved code I spotted at least [this line](https://github.com/originell/jpype/blob/7334efaa9781e3a6e3c2f6a7e30b4e962d9df400/native/common/jp_proxy.cpp#L226) in ```jp_proxy.cpp``` where the refcount to the host JProxy AFAICT is incremented in ```copy```, but the resulting pointer is not freed again anywhere.

**Comment by marscher** [comment]
it looks indeed like there is an additional unnecessary copy in line
226. Have you tried removing this copy? One copy is released in the
destructor.

**Comment by jaseg** [comment]
I just tried that. That reduces the refcount from two to one dangling reference. 🎉

**Comment by jaseg** [comment]
Ok, I think I have found the other issue. However I'm a bit out of my comfort zone here so please double check my theory.

With ```HostRef::copy``` in its constructor and ```HostRef::release``` in its destructore, ```JPProxy``` holds a reference to the python ```JProxy```. Since ```JPProxy``` is only released when ```JProxy``` is destroyed, this constitutes a circular reference. Removing the ```copy``` in the constructor of ```JPProxy``` and the ```release``` in its destructor, the above test script stopped leaking.

**Comment by marscher** [comment]
This is a good spot! However I'm unsure of the implications if we remove this. Could it be that python proxy is only used by the java side, but not referenced directly by any python code?!

**Comment by jaseg** [comment]
Ok, it wasn't quite as simple in the end but [this commit](https://github.com/jaseg/jpype/commit/36c499ead57d69adbb0997c492ec665858f8f580) seems to fix the python end on superficial testing.

The main change is that JPProxy does no longer hold any references to the corresponding JProxy. This means python's gc can do its job when the corresponding JProxy goes out of scope. In this case, the JPProxy gets taken care of by [deleteJPProxyDestructor](https://github.com/originell/jpype/blob/584b89d8e63dcf3880d97a2098efdbdf18d114c2/native/python/include/py_hostenv.h#L115).

The remaining uncertainty for me is what happens to the other end if one end only gets gc'ed. As far as I understand, previously everything always worked because (at least on the python side) nothing could ever get gc'ed. But now, nothing prevents the python end from gc while the java end might still be alive and kicking. Thus what my current solution really lacks I think is proper cross-linking of both refcounts to make sure both ends stay alive as long as either one is still referenced.

**Comment by Thrameos** [comment]
The solution may be correct, but I am unable to get a good picture of how the proxy system is supposed to work.  The problem here is that we need to hold both a python object and a java object in scope for the duration that either objects are alive.  I took care of all of the java object leaks with the local frame interface with JNI.  But this one is much more complex as we have java objects holding python objects.  The python reference system is more likely to hit circular problems than java so I am a bit less comfortable with it.

To be a solution we would need to ensure
1) The java object lives a long as java holds a reference to the object.  (Pass the created object to java, delete the python object, gc java, check it alive, gc java, and see perhaps if it is now dead.)
2) The python object lives as long as java holds a reference to the object.  (Not sure how to check this other than accessing it after python has lost the access.)
3) The java object lives as long as the python object lives.  (I think this is already ensured by our system.)
4) The python object lives as long as the python holds a reference.  (Making sure that if java gcs the object we don't lose the python object.)

If we can test each of the four cases then it would be a valid solution.

**Comment by Thrameos** [comment]
I have analyzed the fix, but I believe that it did not satisfy the requirement that the scope of the JPProxy be the maximum of both the Java and the Python objects.  The design of JPProxy is fundamentally flawed in that it requires holding a global reference to the java JProxy object. Instead it should produce a new JProxy object each time that the object is passed to java.  These should be left for java to manage lifespan.  If we suffer a performance hit then we can have it use a weak reference to cache.

The key difficulty with this change is I have no idea where the JProxy thunk code is that made the byte code.  We need to overload the equals operator so the clone objects properly have equals.

**Comment by Thrameos** [comment]
I believe this issue is currently resolved in the devel branch and has a worrk around in master.
